!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn:
- mHandle: 105
  mName: CAN Analog (5)
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim$CtreAnalogIn
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO:
- mHandle: 8
  mName: Digital IO 8
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 9
  mName: Digital IO 9
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders:
- mConnectedSpeedControllerHandle: 101
  mHandle: 101
  mName: CAN Encoder (1)
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim$CtreEncoder
- mConnectedSpeedControllerHandle: 102
  mHandle: 102
  mName: CAN Encoder (2)
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim$CtreEncoder
mGyros: []
mPwm:
- mHandle: 1
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 2
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 2
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 101
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 1
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 102
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 2
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 103
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 3
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 104
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 4
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 105
  mMotorModelConfig:
    mGearReduction: 1.0
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.StaticLoadMotorSimulationConfig
    mConversionFactor: 1.0
    mLoad: 1.0
  mName: CAN SC 5
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays: []
mSimulatorComponents: []
mSolenoids:
- mHandle: 64
  mName: Solenoid 64
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 65
  mName: Solenoid 65
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 56
  mName: Solenoid 56
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 57
  mName: Solenoid 57
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 58
  mName: Solenoid 58
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 59
  mName: Solenoid 59
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 60
  mName: Solenoid 60
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 61
  mName: Solenoid 61
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 62
  mName: Solenoid 62
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 63
  mName: Solenoid 63
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
